// Project metadata for the portfolio dashboard
// Note: Star projects (Food Tracker, RPG Chess, Adirondack 46ers, Rising Economies) 
// are now managed separately in src/data/starProjects.js for the cinematic slider
export const projects = [
  {
    id: 'adirondack46ers',
    name: 'Adirondack 46ers',
    category: 'Full-Stack',
    description: 'Event management platform for hiking the 46 High Peaks of the Adirondack Mountains',
    path: '../Adirondack46ers',
    port: 3001,
    clientPort: 5173,
    hasServer: true,
    hasClient: true,
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL', 'React Router'],
    features: [
      'Browse upcoming hiking events',
      'View mountain details',
      'Monthly calendar navigation',
      'RESTful API with Express'
    ],
    thumbnail: '⛰️',
    demoVideo: true
  },
  {
    id: 'rising-economies',
    name: 'Rising Economies',
    category: 'Full-Stack',
    description: 'Interactive data visualization platform for global economic development trends',
    path: '../RisingEconomies',
    port: 3002,
    clientPort: 5174,
    hasServer: true,
    hasClient: true,
    techStack: ['Vanilla JavaScript', 'Node.js', 'Express', 'Vite', 'REST API'],
    features: [
      'Interactive economic visualizations',
      'Country-specific detail pages',
      'Dynamic data rendering',
      'RESTful API backend'
    ],
    thumbnail: '📈'
  },
  {
    id: 'food-tracker',
    name: 'Food Tracker',
    category: 'Full-Stack',
    description: 'Nutrition tracking app that runs as Windows desktop app or web application',
    path: '../Exclusions/FoodTracker',
    port: 3003,
    clientPort: 5175,
    hasServer: true,
    hasClient: true,
    techStack: ['React', 'Node.js', 'Express', 'Electron', 'Chart.js'],
    features: [
      'Daily caloric tracking',
      'Macronutrient visualization',
      'Custom food library',
      'Desktop app with Electron',
      'Offline data storage'
    ],
    thumbnail: '🍎',
    highlight: true
  },
  {
    id: 'unearthed-1',
    name: 'UnEarthed Series #1',
    category: 'Full-Stack',
    description: 'Fossil discovery platform - browse and explore ancient artifacts',
    path: '../UnEarthed_Series/UnEarthed_1',
    port: 3004,
    clientPort: 5176,
    hasServer: true,
    hasClient: true,
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL'],
    features: ['Fossil catalog', 'Detail views', 'Backend API'],
    thumbnail: '🦴'
  },
  {
    id: 'unearthed-2',
    name: 'UnEarthed Series #2',
    category: 'Full-Stack',
    description: 'Enhanced fossil platform with advanced filtering and search',
    path: '../UnEarthed_Series/UnEarthed_2',
    port: 3005,
    clientPort: 5177,
    hasServer: true,
    hasClient: true,
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL'],
    features: ['Advanced filtering', 'Search functionality', 'Enhanced UI'],
    thumbnail: '🦖'
  },
  {
    id: 'unearthed-3',
    name: 'UnEarthed Series #3',
    category: 'Full-Stack',
    description: 'Complete CRUD operations for fossil management',
    path: '../UnEarthed_Series/UnEarthed_3',
    port: 3006,
    clientPort: 5178,
    hasServer: true,
    hasClient: true,
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL'],
    features: ['Create fossils', 'Update records', 'Delete entries', 'Full CRUD'],
    thumbnail: '🦕'
  },
  {
    id: 'unearthed-4',
    name: 'UnEarthed Series #4',
    category: 'Full-Stack',
    description: 'Final evolution with authentication and user management',
    path: '../UnEarthed_Series/4_UnEarthed_4',
    port: 3007,
    clientPort: 5179,
    hasServer: true,
    hasClient: true,
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL', 'Auth'],
    features: ['User authentication', 'Protected routes', 'User management'],
    thumbnail: '🏛️'
  },
  {
    id: 'community-board',
    name: 'Community Board',
    category: 'Frontend',
    description: 'Responsive card-based community resource board',
    path: '../Web102/CommunityBoard',
    port: null,
    clientPort: 5180,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'Vite', 'CSS3', 'Responsive Design'],
    features: ['Responsive cards', 'Community resources', 'Mobile-friendly'],
    thumbnail: '📋'
  },
  {
    id: 'creatorverse',
    name: 'Creatorverse',
    category: 'Full-Stack',
    description: 'Content creator showcase platform',
    path: '../Web102/Creatorverse',
    port: null,
    clientPort: 5181,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'Supabase', 'Vite'],
    features: ['Creator profiles', 'Database integration', 'CRUD operations'],
    thumbnail: '🎨'
  },
  {
    id: 'crypto-hustle',
    name: 'Crypto Hustle',
    category: 'Frontend',
    description: 'Cryptocurrency price tracking and analysis',
    path: '../Web102/Crypto-Hustle',
    port: null,
    clientPort: 5182,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'API Integration', 'Vite'],
    features: ['Live crypto prices', 'API integration', 'Price charts'],
    thumbnail: '💰'
  },
  {
    id: 'crypto-watchlist',
    name: 'Crypto WatchList',
    category: 'Frontend',
    description: 'Personal cryptocurrency watchlist application',
    path: '../Web102/CryptoWatchList',
    port: null,
    clientPort: 5183,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'Local Storage', 'Vite'],
    features: ['Watchlist management', 'Local storage', 'Real-time updates'],
    thumbnail: '📊'
  },
  {
    id: 'flashcards',
    name: 'Flashcards',
    category: 'Frontend',
    description: 'Interactive flashcard study application',
    path: '../Web102/Flashcards',
    port: null,
    clientPort: 5184,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'State Management', 'Vite'],
    features: ['Card flipping', 'Study modes', 'Progress tracking'],
    thumbnail: '🎴'
  },
  {
    id: 'html-scraper',
    name: 'HTML Scraper',
    category: 'Frontend',
    description: 'Web scraping and data extraction tool',
    path: '../Web102/HTML_Scraper',
    port: null,
    clientPort: 5185,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'API Integration', 'Vite'],
    features: ['Web scraping', 'Data extraction', 'API integration'],
    thumbnail: '🔍'
  },
  {
    id: 'daily-dog-gazette',
    name: 'The Daily Dog Gazette',
    category: 'Frontend',
    description: 'Dog news and information platform',
    path: '../Web102/TheDailyDogGazette',
    port: null,
    clientPort: 5186,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'Vite', 'CSS3'],
    features: ['Article display', 'Responsive design', 'Component architecture'],
    thumbnail: '🐕'
  },
  {
    id: 'user-profiles',
    name: 'User Profiles',
    category: 'Frontend',
    description: 'User profile management system',
    path: '../Web102/UserProfiles',
    port: null,
    clientPort: 5187,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'Vite', 'State Management'],
    features: ['Profile creation', 'User management', 'State handling'],
    thumbnail: '👤'
  },
  {
    id: 'weatherstack',
    name: 'Weatherstack',
    category: 'Frontend',
    description: 'Weather forecast application',
    path: '../Web102/Weatherstack',
    port: null,
    clientPort: 5188,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'Weather API', 'Vite'],
    features: ['Weather forecasts', 'API integration', 'Location search'],
    thumbnail: '🌤️'
  },
  {
    id: 'drink-maker',
    name: 'Drink Maker Lab',
    category: 'Frontend',
    description: 'Interactive drink recipe builder',
    path: '../Web102/lab3-DrinkMaker',
    port: null,
    clientPort: 5189,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'Vite', 'Interactive UI'],
    features: ['Recipe builder', 'Interactive interface', 'Component composition'],
    thumbnail: '🍹'
  },
  {
    id: 'pelmeni-clicker',
    name: 'Pelmeni Clicker',
    category: 'Frontend',
    description: 'Incremental clicker game',
    path: '../Web102/lab2-Pelmeni-Clicker/pelmeni-clicker',
    port: null,
    clientPort: 5190,
    hasServer: false,
    hasClient: true,
    techStack: ['React', 'Game Logic', 'Vite'],
    features: ['Clicker mechanics', 'Score tracking', 'Game state'],
    thumbnail: '🥟'
  },
  {
    id: 'rpg-chess',
    name: 'RPG Chess',
    category: 'Full-Stack',
    description: 'Chess game with RPG elements',
    path: '../Chess/RPGChess',
    port: 3008,
    clientPort: 5191,
    hasServer: true,
    hasClient: true,
    techStack: ['React', 'Node.js', 'Game Logic', 'WebSockets'],
    features: ['Chess gameplay', 'RPG mechanics', 'Real-time updates'],
    thumbnail: '♟️',
    highlight: true
  }
];
